name = "cablitz/arcane"
version = "0.1.0"

[target]
environment = "roblox"

[engines]
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.27.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.1", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.14.1", target = "lune" }
blink = { name = "pesde/blink", version = "^0.15.1", target = "lune" }

[dependencies]
vide = { wally = "centau/vide", version = "^0.3.1" }
jabby = { wally = "alicesaidhi/jabby", version = "^0.2.0-rc.9" }
spark = { wally = "nezuo/spark", version = "^0.2.2" }
stateq = { wally = "busycityguy/stateq", version = "^0.0.6" }
planck = { wally = "yetanotherclown/planck", version = "^0.1.0" }
planck-jabby = { wally = "yetanotherclown/planck-jabby", version = "^0.1.0" }
matter-hooks = { wally = "yetanotherclown/planck-matter-hooks", version = "^0.1.0" }
matter = { wally = "matter-ecs/matter", version = "^0.8.5" }
jecs = { wally = "ukendio/jecs", version = "^0.5.3" }